const ADD_MESSAGE = 'ADD_MESSAGE';
const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
const ADD_USER = 'ADD_USER';
const USERS_LIST = 'USERS_LIST';

module.exports = {
  ADD_USER,
  ADD_MESSAGE,
  MESSAGE_RECEIVED,
  USERS_LIST
};
